version: 2
updates:
  - package-ecosystem: npm
    directory: /packages/design
    schedule:
      interval: weekly
    groups:
      package-dependencies:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /apps/design
    schedule:
      interval: weekly
    groups:
      site-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
