import type { SurfaceId, SurfaceRuleId } from "@/lib/design-system/data"

/**
 * The surface rules, dry-run against the Sarj platform.
 *
 * Every overlay in `sarj-ai/platform` (`products/platform/apps/web/src`) as of
 * 28 September 2026: each Dialog, AlertDialog, Sheet, Popover and
 * `window.confirm`, plus the destructive actions that have no surface at all.
 * Picker wrappers inside `components/ui` and the mobile nav sheet are left
 * out — they are primitives, not decisions.
 *
 * Each row says what the reader is doing there, what the platform uses, what
 * the decision picks, and which of the rules it breaks. Paths are relative to
 * that `src`; line numbers are where the overlay opens.
 *
 * One finding is structural rather than per-site: the platform's `Dialog`
 * carries `sm:max-w-lg`, and a consumer passing `max-w-2xl` (no prefix) only
 * replaces the unprefixed max width — so above 640px every one of those
 * dialogs is 512px, whatever it asked for. They are marked "asks N".
 */

export type Doing =
  | "Configuring"
  | "Creating"
  | "Picking"
  | "Reading"
  | "Confirming"
  | "Told it failed"

export type Today =
  | "Dialog"
  | "Alert dialog"
  | "Sheet"
  | "Popover"
  | "Command dialog"
  | "Browser confirm"
  | "Nothing"
  | "Inline"
  | "Page"

export type Verdict =
  | "keep"
  | "reshape"
  | "move"
  | "add-confirm"
  | "drop-confirm"
  | "add-undo"

export const VERDICT_LABEL: Record<Verdict, string> = {
  keep: "Keep",
  reshape: "Reshape",
  move: "Move",
  "add-confirm": "Add confirm",
  "drop-confirm": "Drop confirm",
  "add-undo": "Add undo",
}

export type AuditRow = {
  id: string
  area: string
  what: string
  file: string
  doing: Doing
  today: Today
  /** What the platform renders it at, when that is part of the finding. */
  width?: string
  should: SurfaceId
  verdict: Verdict
  breaks: SurfaceRuleId[]
  fix: string
}

export const SURFACE_AUDIT: AuditRow[] = [
  /* Personas ------------------------------------------------------------- */
  {
    id: "persona-create",
    area: "Personas",
    what: "Create persona",
    file: "app/agents/components/add-agent-profile-dialog.tsx:67",
    doing: "Creating",
    today: "Dialog",
    width: "800",
    should: "page",
    verdict: "move",
    breaks: ["one-at-a-time", "widths"],
    fix: "Five sections and two sheets opened from inside it is the persona itself. Name and language in a dialog, then land on its page.",
  },
  {
    id: "persona-edit",
    area: "Personas",
    what: "Edit persona",
    file: "app/agents/components/edit-agent-profile-dialog.tsx:48",
    doing: "Configuring",
    today: "Dialog",
    width: "800",
    should: "page",
    verdict: "move",
    breaks: ["one-at-a-time", "widths"],
    fix: "The whole object: a persona page with sections, saved through the save bar.",
  },
  {
    id: "persona-discard",
    area: "Personas",
    what: "Discard persona changes",
    file: "app/agents/components/add-agent-profile-dialog.tsx:88",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "keep",
    breaks: [],
    fix: "The guard every form needs, and one of only two the platform has.",
  },
  {
    id: "filler-words",
    area: "Personas",
    what: "Filler words",
    file: "components/settings/backchannel-settings.tsx:252",
    doing: "Configuring",
    today: "Sheet",
    width: "512",
    should: "inline",
    verdict: "move",
    breaks: ["one-at-a-time", "pinned", "footer", "widths"],
    fix: "Opened from inside the persona dialog. A section of the persona page, with the slider absent until there is a word.",
  },
  {
    id: "background-noise",
    area: "Personas",
    what: "Background noise",
    file: "components/settings/background-noise-settings.tsx:98",
    doing: "Configuring",
    today: "Sheet",
    width: "512",
    should: "inline",
    verdict: "move",
    breaks: ["one-at-a-time", "footer", "widths"],
    fix: "Two controls in a sheet on a dialog. A row on the persona page.",
  },
  {
    id: "persona-delete",
    area: "Personas",
    what: "Delete persona",
    file: "app/agents/components/delete-agent-button.tsx:93",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: ["confirm-copy", "red"],
    fix: "“Delete {name}?” and where its scenarios go. The destructive variant, not a bg-destructive class.",
  },
  {
    id: "persona-default",
    area: "Personas",
    what: "Set default persona",
    file: "app/agents/components/set-default-agent-button.tsx:60",
    doing: "Confirming",
    today: "Alert dialog",
    should: "undo",
    verdict: "drop-confirm",
    breaks: ["undo-first", "confirm-copy"],
    fix: "One click to reverse. Set it, and put Undo in the toast.",
  },

  /* Scenarios ------------------------------------------------------------ */
  {
    id: "scenario-archive",
    area: "Scenarios",
    what: "Delete (archive) scenario",
    file: "app/scenarios/scenario-actions.tsx:119",
    doing: "Confirming",
    today: "Nothing",
    should: "undo",
    verdict: "add-undo",
    breaks: ["undo-first", "feedback"],
    fix: "It archives with no word at all. Toast “Moved to Recently deleted” with Undo.",
  },
  {
    id: "scenario-delete",
    area: "Scenarios",
    what: "Delete scenario for good",
    file: "app/scenarios/delete-scenario-dialog.tsx:61",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: ["confirm-copy", "red"],
    fix: "The title is “Are you sure?” over a red triangle. “Delete {name} for good?” and that nothing restores it.",
  },
  {
    id: "scenario-template",
    area: "Scenarios",
    what: "Create template",
    file: "app/scenarios/create-template-button.tsx:105",
    doing: "Creating",
    today: "Dialog",
    width: "512 (asks 576)",
    should: "dialog",
    verdict: "reshape",
    breaks: ["widths"],
    fix: "Three fields fit a dialog. sm:max-w-md.",
  },
  {
    id: "scenario-review",
    area: "Scenarios",
    what: "Review changes before save",
    file: "app/scenarios/scenario-submit-dialog.tsx:147",
    doing: "Confirming",
    today: "Dialog",
    width: "1024",
    should: "drawer",
    verdict: "move",
    breaks: ["widths"],
    fix: "The review drawer from Unsaved changes: a line diff with per-change revert, beside the prompt it describes.",
  },
  {
    id: "scenario-cannot-save",
    area: "Scenarios",
    what: "Cannot save changes",
    file: "app/scenarios/[scenarioId]/scenario-view-edit.tsx:830",
    doing: "Told it failed",
    today: "Alert dialog",
    should: "inline",
    verdict: "move",
    breaks: ["feedback", "footer"],
    fix: "An alert with only “Got it”. Say what is missing on the save bar, next to the button that failed.",
  },
  {
    id: "scenario-cannot-create",
    area: "Scenarios",
    what: "Cannot create scenario",
    file: "app/scenarios/scenario-form.tsx:795",
    doing: "Told it failed",
    today: "Alert dialog",
    should: "inline",
    verdict: "move",
    breaks: ["feedback", "footer"],
    fix: "Same as above: the missing fields, marked on the form.",
  },
  {
    id: "scenario-save-first",
    area: "Scenarios",
    what: "Save scenario first?",
    file: "app/scenarios/scenario-form.tsx:813",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "keep",
    breaks: [],
    fix: "A leave guard with a verb. Sentence case in the title.",
  },
  {
    id: "scenario-ai-notes",
    area: "Scenarios",
    what: "AI suggestions",
    file: "app/scenarios/scenario-form.tsx:762",
    doing: "Reading",
    today: "Sheet",
    width: "320",
    should: "inline",
    verdict: "move",
    breaks: ["widths"],
    fix: "It points at sections of the form it dims. A column beside the form, out of the save bar's corner.",
  },
  {
    id: "scenario-ai-dismiss",
    area: "Scenarios",
    what: "Dismiss all suggestions",
    file: "app/scenarios/ai-notes-sidebar.tsx:284",
    doing: "Confirming",
    today: "Alert dialog",
    should: "undo",
    verdict: "drop-confirm",
    breaks: ["undo-first", "confirm-copy"],
    fix: "Dismiss them, and offer Undo.",
  },
  {
    id: "scenario-transfer-pick",
    area: "Scenarios",
    what: "Pick organisation to transfer to",
    file: "app/scenarios/[scenarioId]/scenario-transfer-ownership.tsx:119",
    doing: "Picking",
    today: "Popover",
    should: "popover",
    verdict: "keep",
    breaks: [],
    fix: "A searchable list anchored to its field.",
  },
  {
    id: "scenario-transfer",
    area: "Scenarios",
    what: "Transfer ownership",
    file: "app/scenarios/[scenarioId]/scenario-transfer-ownership.tsx:193",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: ["confirm-copy"],
    fix: "“Transfer {scenario} to {organisation}?” and who loses access. Primary — nothing is destroyed.",
  },
  {
    id: "scenario-kb-pick",
    area: "Scenarios",
    what: "Attach knowledge bases",
    file: "components/scenario/kb-configuration.tsx:78",
    doing: "Picking",
    today: "Popover",
    should: "popover",
    verdict: "keep",
    breaks: [],
    fix: "The model for every library picker. Add “Create knowledge base” at its foot.",
  },
  {
    id: "scenario-tool-pick",
    area: "Scenarios",
    what: "Add a tool",
    file: "components/scenario/tools-configuration.tsx:425",
    doing: "Picking",
    today: "Command dialog",
    width: "512",
    should: "popover",
    verdict: "move",
    breaks: ["picker"],
    fix: "Same page as the knowledge base picker, different surface. The popover, with “Create tool” at its foot.",
  },
  {
    id: "scenario-tool-config",
    area: "Scenarios",
    what: "Configure a tool",
    file: "components/scenario/tools-configuration.tsx:519",
    doing: "Configuring",
    today: "Sheet",
    width: "512 / 672",
    should: "drawer",
    verdict: "reshape",
    breaks: ["footer", "guard", "widths"],
    fix: "Right surface. Three buttons in the body, primary first; Esc drops every change. Pinned Cancel · Save, one guard, 448.",
  },
  {
    id: "scenario-tool-remove",
    area: "Scenarios",
    what: "Remove a tool",
    file: "components/scenario/tools-configuration.tsx:405",
    doing: "Confirming",
    today: "Nothing",
    should: "undo",
    verdict: "keep",
    breaks: [],
    fix: "A staged edit. The save bar's Discard is its undo.",
  },
  {
    id: "scenario-tool-preview",
    area: "Scenarios",
    what: "Preview a tool's request",
    file: "components/api-endpoint-editor/components/preview-test-modal.tsx:140",
    doing: "Reading",
    today: "Dialog",
    width: "512 (asks 768)",
    should: "drawer",
    verdict: "move",
    breaks: ["one-at-a-time", "pinned", "widths"],
    fix: "A dialog on the tool sheet. One level deeper inside the drawer, with Back.",
  },
  {
    id: "scenario-tool-test",
    area: "Scenarios",
    what: "Test a tool's request",
    file: "components/api-endpoint-editor/components/test-values-form.tsx:212",
    doing: "Creating",
    today: "Dialog",
    width: "512 (asks 672)",
    should: "drawer",
    verdict: "move",
    breaks: ["one-at-a-time", "pinned", "widths"],
    fix: "Three overlays deep. The test inputs sit under the preview, in the same drawer.",
  },
  {
    id: "scenario-criterion-remove",
    area: "Scenarios",
    what: "Remove success criterion",
    file: "components/scenario/success-criteria-form.tsx:153",
    doing: "Confirming",
    today: "Alert dialog",
    should: "undo",
    verdict: "drop-confirm",
    breaks: ["undo-first", "confirm-copy"],
    fix: "A staged edit, like removing a tool, which does not ask. The save bar's Discard covers both.",
  },
  {
    id: "scenario-field-remove",
    area: "Scenarios",
    what: "Remove schema field",
    file: "components/json-schema-editor/schema-property-editor.tsx:238",
    doing: "Confirming",
    today: "Nothing",
    should: "undo",
    verdict: "keep",
    breaks: [],
    fix: "A staged edit. Nothing to add.",
  },
  {
    id: "scenario-field-add",
    area: "Scenarios",
    what: "Add schema field",
    file: "components/json-schema-editor/add-field-button.tsx:82",
    doing: "Creating",
    today: "Dialog",
    width: "1200",
    should: "dialog",
    verdict: "reshape",
    breaks: ["widths", "pinned"],
    fix: "Four inputs in the widest dialog in the app. 448, the example under the fields.",
  },
  {
    id: "scenario-zoho-sink",
    area: "Scenarios",
    what: "Zoho CRM sink",
    file: "components/scenario/advanced-settings-section.tsx:260",
    doing: "Configuring",
    today: "Dialog",
    width: "512 (asks 672)",
    should: "drawer",
    verdict: "move",
    breaks: ["pinned", "footer", "widths"],
    fix: "A module, a search and a field list, scrolling as a whole with no footer. A drawer with Cancel · Save.",
  },
  {
    id: "scenario-zoho-field",
    area: "Scenarios",
    what: "Zoho field and note",
    file: "components/scenario/sinks/zoho-crm-sink-config.tsx:180",
    doing: "Configuring",
    today: "Dialog",
    width: "560",
    should: "drawer",
    verdict: "move",
    breaks: ["one-at-a-time", "widths"],
    fix: "Two dialogs on the sink dialog. One level deeper in the sink drawer, with Back.",
  },
  {
    id: "scenario-new",
    area: "Scenarios",
    what: "Create scenario",
    file: "app/scenarios/new/agent-creation-flow.tsx",
    doing: "Creating",
    today: "Page",
    should: "page",
    verdict: "keep",
    breaks: [],
    fix: "Steps on a page of their own, with Back.",
  },

  /* Knowledge bases ------------------------------------------------------ */
  {
    id: "kb-create",
    area: "Knowledge bases",
    what: "Create knowledge base",
    file: "app/knowledge-bases/knowledge-base-dialog-form.tsx:105",
    doing: "Creating",
    today: "Dialog",
    width: "500",
    should: "dialog",
    verdict: "reshape",
    breaks: ["widths"],
    fix: "Title and description fit. sm:max-w-md.",
  },
  {
    id: "kb-edit",
    area: "Knowledge bases",
    what: "Edit knowledge base",
    file: "app/knowledge-bases/kb-table.tsx:177",
    doing: "Configuring",
    today: "Dialog",
    width: "500",
    should: "dialog",
    verdict: "reshape",
    breaks: ["widths"],
    fix: "Two fields from a list row fit a dialog. sm:max-w-md.",
  },
  {
    id: "kb-delete",
    area: "Knowledge bases",
    what: "Delete knowledge base",
    file: "app/knowledge-bases/delete-kb-dialog.tsx:49",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "keep",
    breaks: [],
    fix: "“Delete {title}?” and one plain line of consequence. The copy to copy.",
  },
  {
    id: "kb-add-files",
    area: "Knowledge bases",
    what: "Add files",
    file: "app/knowledge-bases/add-files-dialog.tsx:194",
    doing: "Creating",
    today: "Dialog",
    width: "576",
    should: "drawer",
    verdict: "move",
    breaks: ["pinned", "guard", "widths"],
    fix: "Language, file and an editable extract; the footer scrolls away. A drawer, with a guard for the edited text.",
  },
  {
    id: "kb-add-text",
    area: "Knowledge bases",
    what: "Add text",
    file: "app/knowledge-bases/add-text-dialog.tsx:86",
    doing: "Creating",
    today: "Dialog",
    width: "576",
    should: "drawer",
    verdict: "move",
    breaks: ["pinned", "guard", "widths"],
    fix: "A long text area that Esc throws away. A drawer, with a guard.",
  },
  {
    id: "kb-preview",
    area: "Knowledge bases",
    what: "Preview a file",
    file: "app/knowledge-bases/file-preview-dialog.tsx:49",
    doing: "Reading",
    today: "Dialog",
    width: "672",
    should: "record",
    verdict: "move",
    breaks: ["record-url", "widths"],
    fix: "Reading one file from a list. The record drawer, in the URL, ↑ ↓ to the next file.",
  },
  {
    id: "kb-file-remove",
    area: "Knowledge bases",
    what: "Remove a file",
    file: "app/knowledge-bases/delete-file-dialog.tsx:48",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "keep",
    breaks: [],
    fix: "“Remove {filename}?” with the destructive variant.",
  },
  {
    id: "kb-description",
    area: "Knowledge bases",
    what: "Edit description",
    file: "app/knowledge-bases/[kbId]/kb-description-field.tsx:87",
    doing: "Configuring",
    today: "Inline",
    should: "inline",
    verdict: "keep",
    breaks: [],
    fix: "One value, edited where it is shown.",
  },

  /* Batch calls ---------------------------------------------------------- */
  {
    id: "batch-settings",
    area: "Batch calls",
    what: "Batch settings",
    file: "app/batch-calls/batch-settings-sheet.tsx:155",
    doing: "Configuring",
    today: "Sheet",
    width: "384",
    should: "drawer",
    verdict: "reshape",
    breaks: ["pinned", "footer", "guard", "widths"],
    fix: "Right surface, wrong shape: a full-width Save in the body and no Cancel. Pinned Cancel · Save, a guard, 448.",
  },
  {
    id: "batch-retry",
    area: "Batch calls",
    what: "Retry failed calls",
    file: "app/batch-calls/retry-batch-button.tsx:60",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: ["confirm-copy"],
    fix: "“Retry 14 failed calls?” with the count, since each one is a call placed again.",
  },
  {
    id: "batch-stop",
    area: "Batch calls",
    what: "Stop batch",
    file: "app/batch-calls/stop-resume-batch-buttons.tsx:61",
    doing: "Confirming",
    today: "Nothing",
    should: "undo",
    verdict: "add-undo",
    breaks: ["undo-first"],
    fix: "Resume exists, so nothing needs asking. Toast “Batch stopped” with Resume as its undo.",
  },
  {
    id: "batch-export",
    area: "Batch calls",
    what: "Export report",
    file: "app/batch-calls/export-batch-button.tsx:77",
    doing: "Configuring",
    today: "Dialog",
    width: "672",
    should: "drawer",
    verdict: "move",
    breaks: ["widths"],
    fix: "The same report configuration as Conversations. See there.",
  },
  {
    id: "batch-scenario-pick",
    area: "Batch calls",
    what: "Pick a scenario",
    file: "components/scenario-select.tsx:46",
    doing: "Picking",
    today: "Popover",
    should: "popover",
    verdict: "keep",
    breaks: [],
    fix: "Right surface. Use the Command list the other pickers use.",
  },
  {
    id: "batch-create",
    area: "Batch calls",
    what: "Create batch",
    file: "app/batch-calls/create/page.tsx",
    doing: "Creating",
    today: "Page",
    should: "page",
    verdict: "keep",
    breaks: [],
    fix: "A CSV needs its preview beside the form. ElevenLabs does the same.",
  },

  /* Conversations -------------------------------------------------------- */
  {
    id: "call-detail",
    area: "Conversations",
    what: "Call detail",
    file: "app/calls/call-detail-sheet.tsx:52",
    doing: "Reading",
    today: "Sheet",
    width: "1152",
    should: "record",
    verdict: "reshape",
    breaks: ["record-url", "widths"],
    fix: "Already in the URL. Add ↑ ↓ through the list, and 1024 so the list shows at the edge.",
  },
  {
    id: "call-flag",
    area: "Conversations",
    what: "Flag a call",
    file: "app/calls/call-flag-dialog.tsx:87",
    doing: "Creating",
    today: "Dialog",
    width: "425",
    should: "popover",
    verdict: "move",
    breaks: ["one-at-a-time", "widths"],
    fix: "A dialog on the call sheet. Two fields anchored to the Flag button: a popover inside the record.",
  },
  {
    id: "call-retry-outcome",
    area: "Conversations",
    what: "Re-run the outcome",
    file: "app/calls/retry-call-outcome-button.tsx:57",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: ["confirm-copy"],
    fix: "“Re-run the outcome?” and that the current one is replaced.",
  },
  {
    id: "call-json",
    area: "Conversations",
    what: "Inspect a JSON cell",
    file: "app/calls/call-table.tsx:91",
    doing: "Reading",
    today: "Popover",
    should: "popover",
    verdict: "keep",
    breaks: [],
    fix: "A quick look at a value too long for its cell.",
  },
  {
    id: "call-report",
    area: "Conversations",
    what: "Configure report",
    file: "app/calls/configure-report-dialog.tsx:398",
    doing: "Configuring",
    today: "Dialog",
    width: "672",
    should: "drawer",
    verdict: "move",
    breaks: ["widths"],
    fix: "A template, three column pickers and reorderable chips is more than four. A drawer — keep its pinned header and footer, the best in the app.",
  },
  {
    id: "call-report-template",
    area: "Conversations",
    what: "Save report template",
    file: "app/calls/configure-report-dialog.tsx:616",
    doing: "Creating",
    today: "Dialog",
    width: "448",
    should: "inline",
    verdict: "move",
    breaks: ["one-at-a-time"],
    fix: "A dialog on a dialog for one field. “Save as template” inline at the foot of the report drawer.",
  },
  {
    id: "call-filters",
    area: "Conversations",
    what: "Organisation and scenario filters",
    file: "components/scenario-selector.tsx:142",
    doing: "Picking",
    today: "Popover",
    should: "popover",
    verdict: "keep",
    breaks: [],
    fix: "Anchored, searchable, no footer.",
  },
  {
    id: "dashboard-period",
    area: "Conversations",
    what: "Dashboard date range",
    file: "app/dashboard/period-selector.tsx:196",
    doing: "Picking",
    today: "Popover",
    should: "popover",
    verdict: "keep",
    breaks: [],
    fix: "Two months of calendar, anchored to the range.",
  },

  /* Messaging ------------------------------------------------------------ */
  {
    id: "messaging-detail",
    area: "Messaging",
    what: "Messaging session",
    file: "app/messaging/messaging-detail-sheet.tsx:45",
    doing: "Reading",
    today: "Sheet",
    width: "896",
    should: "record",
    verdict: "reshape",
    breaks: ["record-url", "widths"],
    fix: "The same kind of record as a call at a different width, with no padding. 1024, the call sheet's padding, ↑ ↓.",
  },
  {
    id: "messaging-config-add",
    area: "Messaging",
    what: "Add messaging configuration",
    file: "app/messaging-settings/components/add-config-dialog.tsx:161",
    doing: "Creating",
    today: "Dialog",
    width: "600",
    should: "drawer",
    verdict: "move",
    breaks: ["pinned", "guard", "widths"],
    fix: "Six fields and rows that grow, scrolling as a whole. A drawer.",
  },
  {
    id: "messaging-config-edit",
    area: "Messaging",
    what: "Edit messaging configuration",
    file: "app/messaging-settings/components/edit-config-dialog.tsx:120",
    doing: "Configuring",
    today: "Dialog",
    width: "600",
    should: "drawer",
    verdict: "move",
    breaks: ["pinned", "guard", "widths"],
    fix: "The same form. The same drawer, with Save off until something changes.",
  },
  {
    id: "messaging-config-delete",
    area: "Messaging",
    what: "Delete messaging configuration",
    file: "app/messaging-settings/components/delete-config-dialog.tsx:54",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: ["confirm-copy"],
    fix: "Say which inboxes stop answering, not “are you sure”.",
  },

  /* Integrations --------------------------------------------------------- */
  {
    id: "integration-configure",
    area: "Integrations",
    what: "Connect an integration",
    file: "app/integrations/integration-modal.tsx:218",
    doing: "Configuring",
    today: "Dialog",
    width: "448",
    should: "dialog",
    verdict: "keep",
    breaks: [],
    fix: "An API key, or one connect button. Fits.",
  },
  {
    id: "integration-disconnect",
    area: "Integrations",
    what: "Disconnect an integration",
    file: "app/integrations/integration-modal.tsx:83",
    doing: "Confirming",
    today: "Nothing",
    should: "confirm",
    verdict: "add-confirm",
    breaks: ["undo-first"],
    fix: "Tools that use it fail mid-call. “Disconnect Zoho?” naming them.",
  },
  {
    id: "zoho-webhook-create",
    area: "Integrations",
    what: "Create Zoho webhook",
    file: "app/integrations/zoho/management/webhook-management-client.tsx:254",
    doing: "Creating",
    today: "Dialog",
    width: "1024",
    should: "drawer",
    verdict: "move",
    breaks: ["pinned", "widths"],
    fix: "Two columns and a conditions builder that grows, with no height limit. A drawer.",
  },
  {
    id: "zoho-webhook-duplicate",
    area: "Integrations",
    what: "Duplicate webhook warning",
    file: "app/integrations/zoho/management/webhook-management-client.tsx:575",
    doing: "Confirming",
    today: "Dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: ["red"],
    fix: "A confirm over the drawer is fine. “Create anyway” is primary — it creates, it does not destroy.",
  },
  {
    id: "zoho-webhook-delete",
    area: "Integrations",
    what: "Delete Zoho webhook",
    file: "app/integrations/zoho/management/webhook-table.tsx:205",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: ["confirm-copy", "red"],
    fix: "An amber triangle and “are you sure”. Name the webhook, say which events stop.",
  },

  /* Developers ----------------------------------------------------------- */
  {
    id: "api-key-create",
    area: "Developers",
    what: "Create API key",
    file: "app/api-keys/client.tsx:125",
    doing: "Creating",
    today: "Alert dialog",
    should: "dialog",
    verdict: "move",
    breaks: ["undo-first"],
    fix: "“Create API key?” asks about something harmless. A dialog with a Name, then the key once, in the same dialog.",
  },
  {
    id: "api-key-delete",
    area: "Developers",
    what: "Delete API key",
    file: "app/api-keys/client.tsx:318",
    doing: "Confirming",
    today: "Dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: ["confirm-copy"],
    fix: "An alert dialog, and the consequence: calls made with this key start failing.",
  },
  {
    id: "variables-edit",
    area: "Developers",
    what: "Create and edit variables",
    file: "app/variables/client.tsx",
    doing: "Configuring",
    today: "Inline",
    should: "inline",
    verdict: "keep",
    breaks: [],
    fix: "Edited in the row it lives in.",
  },
  {
    id: "variables-delete",
    area: "Developers",
    what: "Delete variable",
    file: "app/variables/client.tsx:144",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: ["red"],
    fix: "Scenarios that use it lose the value. Destructive variant, and say which.",
  },
  {
    id: "webhooks-form",
    area: "Developers",
    what: "Webhook settings",
    file: "app/webhooks/webhook-inner.tsx",
    doing: "Configuring",
    today: "Inline",
    should: "inline",
    verdict: "keep",
    breaks: [],
    fix: "A settings page with its own tester. Fits.",
  },
  {
    id: "webhooks-delete",
    area: "Developers",
    what: "Delete webhook",
    file: "app/webhooks/webhook-inner.tsx:168",
    doing: "Confirming",
    today: "Nothing",
    should: "confirm",
    verdict: "add-confirm",
    breaks: ["undo-first"],
    fix: "A danger-zone button that deletes on the click, while the Zoho webhook asks. Confirm, naming what stops arriving.",
  },
  {
    id: "connection-create",
    area: "Developers",
    what: "Create auth connection",
    file: "app/authentication/connection-dialogs.tsx:668",
    doing: "Creating",
    today: "Dialog",
    width: "480",
    should: "drawer",
    verdict: "move",
    breaks: ["pinned", "footer", "widths"],
    fix: "OAuth2 is eight fields and two repeaters, with no Cancel. A drawer.",
  },
  {
    id: "connection-edit",
    area: "Developers",
    what: "Edit auth connection",
    file: "app/authentication/connection-dialogs.tsx:808",
    doing: "Configuring",
    today: "Dialog",
    width: "420",
    should: "dialog",
    verdict: "reshape",
    breaks: ["footer", "widths"],
    fix: "Two fields fit. Add Cancel; 448.",
  },
  {
    id: "connection-rotate",
    area: "Developers",
    what: "Rotate secret",
    file: "app/authentication/connection-dialogs.tsx:991",
    doing: "Creating",
    today: "Dialog",
    width: "420",
    should: "dialog",
    verdict: "reshape",
    breaks: ["footer", "widths"],
    fix: "Add Cancel; 448.",
  },
  {
    id: "connection-delete",
    area: "Developers",
    what: "Delete auth connection",
    file: "app/authentication/connections-table.tsx:407",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: ["red"],
    fix: "Delete in primary. Destructive, and name the tools that use it.",
  },

  /* Playground ----------------------------------------------------------- */
  {
    id: "playground-mode",
    area: "Playground",
    what: "Switch mode mid-conversation",
    file: "app/(playground)/mode-switch-dialog.tsx:20",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: ["confirm-copy"],
    fix: "“End this conversation?” — the conversation is what is lost.",
  },
  {
    id: "playground-agent",
    area: "Playground",
    what: "Switch agent mid-conversation",
    file: "app/(playground)/scenario-switch-dialog.tsx:20",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: ["confirm-copy"],
    fix: "The same question as switching mode, with the same words.",
  },

  /* Admin ---------------------------------------------------------------- */
  {
    id: "admin-org-create",
    area: "Admin",
    what: "Create organisation",
    file: "app/admin/organizations/create-organization-dialog.tsx:30",
    doing: "Creating",
    today: "Dialog",
    width: "425",
    should: "dialog",
    verdict: "reshape",
    breaks: ["footer", "widths"],
    fix: "One field, with Submit and no Cancel. Cancel · Create organisation; 448.",
  },
  {
    id: "admin-user-create",
    area: "Admin",
    what: "Create user",
    file: "app/admin/organizations/create-user-dialog.tsx:39",
    doing: "Creating",
    today: "Dialog",
    width: "425",
    should: "dialog",
    verdict: "reshape",
    breaks: ["footer", "widths"],
    fix: "Same as above.",
  },
  {
    id: "admin-member-add",
    area: "Admin",
    what: "Add member",
    file: "app/admin/organizations/[id]/add-member-dialog.tsx:43",
    doing: "Creating",
    today: "Dialog",
    width: "425",
    should: "dialog",
    verdict: "reshape",
    breaks: ["footer", "widths"],
    fix: "Same as above.",
  },
  {
    id: "admin-user-remove",
    area: "Admin",
    what: "Remove user from organisation",
    file: "app/admin/organizations/user-row.tsx:77",
    doing: "Confirming",
    today: "Nothing",
    should: "confirm",
    verdict: "add-confirm",
    breaks: ["undo-first", "red"],
    fix: "A plain button that removes someone's access. Confirm it, in red.",
  },
  {
    id: "admin-industry-create",
    area: "Admin",
    what: "Create industry",
    file: "app/admin/scenario-templates/agent-industry-form.tsx:67",
    doing: "Creating",
    today: "Dialog",
    width: "512 (asks 672)",
    should: "dialog",
    verdict: "reshape",
    breaks: ["widths"],
    fix: "Name and icon fit. 448 — and one form for create and edit.",
  },
  {
    id: "admin-industry-edit",
    area: "Admin",
    what: "Edit industry",
    file: "app/admin/scenario-templates/edit-industry-dialog.tsx:83",
    doing: "Configuring",
    today: "Dialog",
    width: "512",
    should: "dialog",
    verdict: "reshape",
    breaks: ["widths"],
    fix: "A second copy of the form above, worded differently. Use that one.",
  },
  {
    id: "admin-industry-delete",
    area: "Admin",
    what: "Delete industry",
    file: "app/admin/scenario-templates/delete-industry-button.tsx:19",
    doing: "Confirming",
    today: "Browser confirm",
    should: "confirm",
    verdict: "reshape",
    breaks: ["confirm-copy", "red"],
    fix: "The browser's own box. A confirm, naming the use cases that go with it.",
  },
  {
    id: "admin-use-case-delete",
    area: "Admin",
    what: "Delete use case",
    file: "app/admin/scenario-templates/[industryId]/delete-use-case-button.tsx:19",
    doing: "Confirming",
    today: "Browser confirm",
    should: "confirm",
    verdict: "reshape",
    breaks: ["confirm-copy", "red"],
    fix: "Same as above.",
  },
  {
    id: "admin-section-create",
    area: "Admin",
    what: "Create global prompt section",
    file: "app/admin/global-prompts/create-section-dialog.tsx:81",
    doing: "Creating",
    today: "Dialog",
    width: "512 (asks 672)",
    should: "drawer",
    verdict: "move",
    breaks: ["pinned", "widths"],
    fix: "Four fields, conditional ones, and the prompt content. A drawer.",
  },
  {
    id: "admin-prompt-review",
    area: "Admin",
    what: "Review global prompt changes",
    file: "app/admin/global-prompts/global-prompt-review-dialog.tsx:83",
    doing: "Confirming",
    today: "Dialog",
    width: "512 (asks 1024)",
    should: "drawer",
    verdict: "move",
    breaks: ["widths"],
    fix: "A side-by-side diff squeezed to 512. The review drawer from Unsaved changes.",
  },
  {
    id: "admin-settings-publish",
    area: "Admin",
    what: "Save settings for all",
    file: "app/admin/global-settings/publish-confirmation-dialog.tsx:67",
    doing: "Confirming",
    today: "Alert dialog",
    width: "512 (asks 896)",
    should: "drawer",
    verdict: "move",
    breaks: ["widths", "footer"],
    fix: "Three tabs inside an alert, and “Yes, Save for All”. The review drawer; the button says “Save for all organisations”.",
  },
  {
    id: "admin-settings-personal",
    area: "Admin",
    what: "Save a personal override",
    file: "app/admin/global-settings/save-personal-confirmation-dialog.tsx:41",
    doing: "Confirming",
    today: "Alert dialog",
    width: "512 (asks 896)",
    should: "drawer",
    verdict: "move",
    breaks: ["widths"],
    fix: "The same review, for one person. The same drawer.",
  },
  {
    id: "admin-voice-add",
    area: "Admin",
    what: "Add voice",
    file: "app/admin/voices/components/add-voice-dialog.tsx:31",
    doing: "Creating",
    today: "Dialog",
    width: "512 (asks 672)",
    should: "drawer",
    verdict: "move",
    breaks: ["pinned", "widths"],
    fix: "Ten fields that change with the provider, scrolling as a whole. A drawer.",
  },
  {
    id: "admin-voice-edit",
    area: "Admin",
    what: "Edit voice",
    file: "app/admin/voices/components/edit-voice-dialog.tsx:21",
    doing: "Configuring",
    today: "Dialog",
    width: "512 (asks 576)",
    should: "drawer",
    verdict: "move",
    breaks: ["widths"],
    fix: "Five fields is past four. The same drawer as Add voice.",
  },
  {
    id: "admin-number-register",
    area: "Admin",
    what: "Register a number",
    file: "app/admin/phone-numbers/provisioned/register-number-dialog.tsx:37",
    doing: "Creating",
    today: "Dialog",
    width: "672",
    should: "drawer",
    verdict: "move",
    breaks: ["pinned", "footer", "widths"],
    fix: "Ten fields, the primary first and left-aligned, scrolling as a whole. A drawer.",
  },
  {
    id: "admin-number-org",
    area: "Admin",
    what: "Change a number's organisation",
    file: "app/admin/phone-numbers/provisioned/change-organization-dialog.tsx:72",
    doing: "Configuring",
    today: "Dialog",
    width: "512",
    should: "dialog",
    verdict: "reshape",
    breaks: ["widths"],
    fix: "A pick and a Save. 448.",
  },
  {
    id: "admin-number-outbound",
    area: "Admin",
    what: "Manage outbound",
    file: "app/admin/phone-numbers/provisioned/manage-outbound-dialog.tsx:70",
    doing: "Configuring",
    today: "Dialog",
    width: "512",
    should: "dialog",
    verdict: "reshape",
    breaks: ["widths"],
    fix: "Fits. 448.",
  },
  {
    id: "admin-number-allocation",
    area: "Admin",
    what: "Change allocation",
    file: "app/admin/phone-numbers/provisioned/change-allocation-dialog.tsx:124",
    doing: "Configuring",
    today: "Dialog",
    width: "512",
    should: "dialog",
    verdict: "reshape",
    breaks: ["widths"],
    fix: "A checkbox stands in for a confirm. Say the consequence in the dialog instead; 448.",
  },
  {
    id: "admin-number-link",
    area: "Admin",
    what: "Link a connection",
    file: "app/admin/phone-numbers/provisioned/link-connection-dialog.tsx:67",
    doing: "Picking",
    today: "Dialog",
    width: "512",
    should: "popover",
    verdict: "move",
    breaks: ["picker"],
    fix: "One combobox in a dialog. The combobox, in the row.",
  },
  {
    id: "admin-number-trunk",
    area: "Admin",
    what: "Edit trunk",
    file: "app/admin/phone-numbers/provisioned/edit-trunk-dialog.tsx:97",
    doing: "Configuring",
    today: "Dialog",
    width: "512",
    should: "dialog",
    verdict: "reshape",
    breaks: ["widths"],
    fix: "Fits. 448.",
  },
  {
    id: "admin-number-inbound",
    area: "Admin",
    what: "Assign inbound",
    file: "app/admin/phone-numbers/provisioned/assign-inbound-dialog.tsx:104",
    doing: "Configuring",
    today: "Dialog",
    width: "512",
    should: "dialog",
    verdict: "reshape",
    breaks: ["widths"],
    fix: "Fits. 448.",
  },
  {
    id: "admin-number-direction",
    area: "Admin",
    what: "Number direction",
    file: "components/phone-number-direction-dialog.tsx:73",
    doing: "Configuring",
    today: "Dialog",
    width: "512",
    should: "inline",
    verdict: "move",
    breaks: [],
    fix: "One value. A select in the row it belongs to.",
  },
  {
    id: "admin-number-unlink",
    area: "Admin",
    what: "Unlink a connection",
    file: "app/admin/phone-numbers/provisioned/unlink-connection-dialog.tsx:45",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "keep",
    breaks: [],
    fix: "Primary is right: nothing is destroyed.",
  },
  {
    id: "admin-number-remove-inbound",
    area: "Admin",
    what: "Remove inbound",
    file: "app/admin/phone-numbers/provisioned/remove-inbound-dialog.tsx:43",
    doing: "Confirming",
    today: "Dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: [],
    fix: "A plain dialog, so an outside click answers it. An alert dialog.",
  },
  {
    id: "admin-number-shared",
    area: "Admin",
    what: "Shared organisations",
    file: "app/admin/phone-numbers/provisioned/shared-orgs-cell.tsx:28",
    doing: "Reading",
    today: "Dialog",
    width: "512",
    should: "popover",
    verdict: "move",
    breaks: [],
    fix: "A read-only list with no footer. A popover on the cell.",
  },
  {
    id: "admin-number-deactivate",
    area: "Admin",
    what: "Deactivate a number",
    file: "app/admin/phone-numbers/provisioned/phone-number-row-actions.tsx:287",
    doing: "Confirming",
    today: "Nothing",
    should: "confirm",
    verdict: "add-confirm",
    breaks: ["undo-first", "typed"],
    fix: "A number that takes calls stops on one click. Confirm, typing the number.",
  },
  {
    id: "admin-number-transfer",
    area: "Admin",
    what: "Transfer toggle",
    file: "app/admin/phone-numbers/provisioned/phone-number-row-actions.tsx:275",
    doing: "Confirming",
    today: "Nothing",
    should: "confirm",
    verdict: "add-confirm",
    breaks: ["undo-first"],
    fix: "Changes where live calls go. Confirm.",
  },
  {
    id: "admin-connection-verify",
    area: "Admin",
    what: "Verify a connection",
    file: "app/admin/phone-numbers/connections/[sipConnectionId]/verify-connection-dialog.tsx:48",
    doing: "Reading",
    today: "Dialog",
    width: "512",
    should: "dialog",
    verdict: "reshape",
    breaks: ["footer"],
    fix: "Close sits after Run checks. Close, then Run checks.",
  },
  {
    id: "admin-connection-pings",
    area: "Admin",
    what: "Outbound pings",
    file: "app/admin/phone-numbers/connections/[sipConnectionId]/outbound-pings-dialog.tsx:95",
    doing: "Reading",
    today: "Dialog",
    width: "512",
    should: "dialog",
    verdict: "keep",
    breaks: [],
    fix: "A short list with a toggle per row.",
  },
  {
    id: "admin-connection-activate",
    area: "Admin",
    what: "Mark connection active",
    file: "app/admin/phone-numbers/connections/[sipConnectionId]/activate-connection-dialog.tsx:47",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "keep",
    breaks: [],
    fix: "It puts live traffic on the trunk. Worth asking.",
  },
  {
    id: "admin-connection-disable",
    area: "Admin",
    what: "Disable a connection",
    file: "app/admin/phone-numbers/connections/[sipConnectionId]/disable-connection-dialog.tsx:45",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: ["red"],
    fix: "The trigger is red and the confirm is primary. Red on the confirm; say which numbers stop.",
  },
  {
    id: "admin-connection-format",
    area: "Admin",
    what: "Number format",
    file: "app/admin/phone-numbers/connections/[sipConnectionId]/number-format-dialog.tsx:71",
    doing: "Configuring",
    today: "Dialog",
    width: "512",
    should: "inline",
    verdict: "move",
    breaks: [],
    fix: "One select. Edit it where the format is shown.",
  },
  {
    id: "admin-connection-link-number",
    area: "Admin",
    what: "Link a number",
    file: "app/admin/phone-numbers/connections/[sipConnectionId]/link-number-dialog.tsx:66",
    doing: "Picking",
    today: "Dialog",
    width: "512",
    should: "popover",
    verdict: "move",
    breaks: ["picker"],
    fix: "One combobox in a dialog. A popover on the Link button.",
  },
  {
    id: "admin-connection-unlink-number",
    area: "Admin",
    what: "Unlink a number",
    file: "app/admin/phone-numbers/connections/[sipConnectionId]/unlink-number-dialog.tsx:49",
    doing: "Confirming",
    today: "Alert dialog",
    should: "confirm",
    verdict: "keep",
    breaks: [],
    fix: "Primary is right: nothing is destroyed.",
  },
  {
    id: "admin-connection-new",
    area: "Admin",
    what: "New SIP connection",
    file: "app/admin/phone-numbers/connections/new/connection-wizard.tsx",
    doing: "Creating",
    today: "Page",
    should: "page",
    verdict: "keep",
    breaks: [],
    fix: "Six steps on a page, with a progress bar and Back.",
  },
  {
    id: "admin-trunk-assign",
    area: "Admin",
    what: "Assign a trunk",
    file: "app/admin/phone-numbers/outbound-trunks/assign-trunk-dialog.tsx:53",
    doing: "Picking",
    today: "Dialog",
    width: "512",
    should: "popover",
    verdict: "move",
    breaks: ["picker"],
    fix: "One combobox in a dialog. A popover on the Assign button.",
  },
  {
    id: "admin-trunk-default",
    area: "Admin",
    what: "Set default trunk",
    file: "app/admin/phone-numbers/outbound-trunks/trunk-assignments-table.tsx:261",
    doing: "Confirming",
    today: "Nothing",
    should: "undo",
    verdict: "add-undo",
    breaks: ["feedback"],
    fix: "Reversible, like the default persona — which asks. Both: set it, Undo in the toast.",
  },
  {
    id: "admin-trunk-unassign",
    area: "Admin",
    what: "Unassign a trunk",
    file: "app/admin/phone-numbers/outbound-trunks/trunk-assignments-table.tsx:276",
    doing: "Confirming",
    today: "Nothing",
    should: "confirm",
    verdict: "add-confirm",
    breaks: ["undo-first"],
    fix: "Outbound calls on it stop. Confirm, naming the organisation.",
  },
  {
    id: "admin-provider-create",
    area: "Admin",
    what: "Create provider",
    file: "app/admin/phone-numbers/providers/create-provider-dialog.tsx:102",
    doing: "Creating",
    today: "Dialog",
    width: "512",
    should: "dialog",
    verdict: "reshape",
    breaks: ["widths"],
    fix: "Two fields fit. 448.",
  },
  {
    id: "admin-provider-rename",
    area: "Admin",
    what: "Rename provider",
    file: "app/admin/phone-numbers/providers/rename-provider-dialog.tsx:66",
    doing: "Configuring",
    today: "Dialog",
    width: "512",
    should: "inline",
    verdict: "move",
    breaks: [],
    fix: "One value. Rename in place.",
  },
  {
    id: "admin-provider-deprecate",
    area: "Admin",
    what: "Deprecate provider",
    file: "app/admin/phone-numbers/providers/provider-row-actions.tsx:83",
    doing: "Confirming",
    today: "Nothing",
    should: "confirm",
    verdict: "add-confirm",
    breaks: ["undo-first"],
    fix: "Its numbers stop being offered. Confirm, with the count.",
  },
  {
    id: "admin-block-number",
    area: "Admin",
    what: "Block a number",
    file: "app/admin/phone-numbers/call-activity/block-number-dialog.tsx:45",
    doing: "Confirming",
    today: "Dialog",
    should: "confirm",
    verdict: "reshape",
    breaks: ["confirm-copy", "red"],
    fix: "A plain dialog, “are you sure”, and a primary Block. An alert dialog: “Block {number}?”, in red.",
  },
]
